### ISSUE TITLE
Missing build.gradle dependency

### ISSUE THREAD

**Issue by llcawthorne** [micronaut-guides/micronaut-token-propagation#1]
On this tutorial, it fails to tell us to add a dependency to build.gradle before trying to make the AuthenticationProviderUserPassword class, so all the imports show up broken.  In other documents, this was included by including a dependency.adoc.  The dependency is question is just security-jwt:

compile "io.micronaut:micronaut-security-jwt"

I'll see about forking the repo and trying to correct this later if I have time.  This issue should remind me if nothing else.  I saw the note on one of my other issues about how to find those common docs, so I'll try to fix these little things I'm finding.

It looks like the same import is needed in the userecho project so it can find @Secured.

**Comment by ilopmar** [comment]
I added the missing dependency to the guide. Just for the future keep in mind that we forget to add something to the guide but if you take a look at the code, everything should be there.
